# name: Receipt
# on: push
# jobs:
#     receipt:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Deployment Receipt
#               run: |
#                 echo "============================="
#                 echo "Deployment Receipt"
#                 echo "============================="
#                 echo ""
#                 echo "Repository : ${{github.event.repository.name}}"
#                 echo "Branch     : ${{github.ref_name}}"
#                 echo "TrigerredBy: ${{github.actor}}" 
#                 echo "EventType  : ${{github.event_name}}"
#                 echo ""
#                 echo "Timestamp : $(date -u)"
#                 echo ""
#                 echo "================================="

