name: Handle Issues
on:
  issues:
    types: [opened, edited, closed]
jobs:
  log-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue details
        env:
          EVENT_JSON: ${{ toJSON(github.event) }}
        run: echo "$EVENT_JSON"